print ("Ingrese nombre, edad, estatura, peso, título, ubicación y escribe sin si no tienes pareja y con si tienes:\n")
nom=input("Nombre: ")
edad=str(input("Edad: "))
est=input("Estatura: ")
peso=input("Peso: ")
car=input("Título: ")
camp=input("Ubicación: ")
par=input("Estado: ")
print ("\nBienvenido ",nom,",",car," de ",camp,".Tienes ",edad," años, pesas ",peso,"kilos(marrano), mides ",est," metros y existes",par," amor.")
